"""Downstream analysis for RNA-Seq data.

Workflow for generating downstream files on RNA-Seq data specifically.
"""
import pandas as pd

# Setup tempdir to work with lscratch
TMPDIR = os.path.join('/lscratch', os.getenv('SLURM_JOBID'))
shell.prefix("set -euo pipefail; export TMPDIR={};".format(TMPDIR))

# Set working dir
workdir: '.'

# import config
configfile: '../config/reference_config.yaml'

patterns = {
    'stringtie': '../output/rnaseq-analysis-wf/{srx}.stringtie.gtf',
}

metadata = pd.read_parquet('../output/metadata-wf/select_library_strategy.parquet')
srxs = metadata[metadata.Fear_et_al_library_strategy.str.contains('RNA-Seq')].index.tolist()

rule targets:
    input: expand(patterns['stringtie'], srx=srxs)


rule stringTie:
    input:
        bam = '../output/aln-wf/samples/{srx}/{srx}.bam',
        gtf = config['references']['dmel']['gtf'],
    output: patterns['stringtie']
    threads: 2
    resources:
      mem_gb=lambda wildcards, attempt: attempt * 1,
      time_hr=lambda wildcards, attempt: attempt * 1
    script: 'scripts/stringtie.py'

