channels:
  - conda-forge
  - bioconda
  - defaults
  - lcdb
  - jfear
dependencies:
  - black
  - feather-format
  - gffutils
  - hdf5
  - ipython
  - jupyter
  - matplotlib
  - nltk
  - notebook
  - pint
  - pyarrow
  - pybedtools
  - pylint
  - pymongo
  - pytables
  - scikit-learn
  - scipy
  - seaborn
  - sramongo >=1.2.0
  - svgutils
  - umap-learn
