name: ncbi_remap
channels:
  - conda-forge
  - bioconda
  - defaults
  - lcdb
  - jfear
dependencies:
  - black=19.3b0
  - bokeh=1.3.4
  - dask=2.4.0
  - feather-format=0.4.0
  - hdf5=1.10.5
  - ipython=7.8.0
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - numpy=1.17.2
  - pandas=0.25.1
  - pyarrow=0.14.1
  - pylint=2.3.1
  - pymongo=3.8.0
  - pytables=3.5.2
  - python=3.7.3
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - snakemake=5.6.0
