name: ncbi_remap
channels: !!python/tuple
- jfear
- lcdb
- bioconda
- r
- daler
- defaults
- conda-forge
dependencies:
- anaconda-client=1.6.0
- argcomplete=1.0.0
- bioconda::ucsc-bigwigmerge=332
- bioconda::argh=0.26.2
- bioconda::bcftools=1.3.1
- bioconda::bamtools=2.4.0
- bioconda::bedtools=2.26.0
- bioconda::biopython=1.68
- bioconda::curl=7.45.0
- bioconda::deeptools=2.4.1
- bioconda::entrez-direct=5.80
- bioconda::fastqc=0.11.5
- bioconda::gffutils=0.8.7.1
- bioconda::hisat2=2.0.5
- bioconda::htslib=1.3.1
- bioconda::mmtf-python=1.0.5
- bioconda::multiqc=0.9
- bioconda::perl-threaded=5.22.0
- bioconda::py2bit=0.2.0
- bioconda::pybedtools=0.7.8
- bioconda::pybigwig=0.2.8
- bioconda::pyfaidx=0.4.7.1
- bioconda::pysam=0.9.1.4
- bioconda::python-dateutil=2.3
- bioconda::samtools=1.3.1
- bioconda::simplejson=3.8.1
- bioconda::snakemake=3.10.1
- bioconda::ucsc-bedgraphtobigwig=332
- clyent=1.2.2
- cycler=0.10.0
- jfear::sratoolkit=2.8.1
- jfear::ipycache=0.1.6dev
- decorator=4.0.10
- entrypoints=0.2.2
- greenlet=0.4.10
- ipykernel=4.5.2
- ipython=5.1.0
- ipython_genutils=0.1.0
- ipywidgets=5.2.2
- jedi=0.9.0
- jfear::blinker=1.4
- jfear::mongodb=3.4.1
- jfear::mongoengine=0.11.0
- jfear::neovim=0.1.12
- jfear::sphinxcontrib-napoleon=0.6.0
- jfear::watermark=1.3.1
- jinja2=2.8
- jsonschema=2.5.1
- lcdb::lcdblib=0.1
- libgcc=5.2.0
- libgfortran=3.0.0
- libsodium=1.0.10
- markupsafe=0.23
- matplotlib=1.5.3
- mistune=0.7.3
- mkl=11.3.3
- msgpack-python=0.4.8
- numpy=1.11.2
- openssl=1.0.2j
- pandas=0.19.1
- path.py=8.2.1
- pexpect=4.0.1
- pickleshare=0.7.4
- pip=9.0.1
- prompt_toolkit=1.0.9
- ptyprocess=0.5.1
- py=1.4.31
- pybedtools=0.7.8
- pygments=2.1.3
- pymongo=3.3.0
- pysam=0.9.1.4
- pytest=3.0.5
- python=3.5.2
- pytz=2016.10
- pyyaml=3.12
- pyzmq=16.0.2
- readline=6.2
- reportlab=3.2.0
- requests=2.12.3
- scipy=0.18.1
- seaborn=0.7.1
- setuptools=27.2.0
- simplegeneric=0.8.1
- six=1.10.0
- sphinx=1.5.1
- sqlite=3.13.0
- terminado=0.6
- tk=8.5.18
- tornado=4.4.2
- traitlets=4.3.1
- wcwidth=0.1.7
- wheel=0.29.0
- widgetsnbextension=1.2.6
- wrapt=1.10.8
- xz=5.2.2
- yaml=0.1.6
- zeromq=4.1.5
- zlib=1.2.8
