channels:
- bioconda
- conda-forge
- defaults
- lcdb
- jfear
dependencies:
- atropos=1.1.10=py36_0
- bamtools=2.4.1=0
- bcftools=1.5=3
- bedtools=2.26.0=0
- bioconductor-annotate=1.56.0=r3.4.1_0
- bioconductor-annotationdbi=1.40.0=r3.4.1_0
- bioconductor-annotationhub=2.10.1=r3.4.1_0
- bioconductor-biobase=2.38.0=r3.4.1_0
- bioconductor-biocgenerics=0.24.0=r3.4.1_0
- bioconductor-biocinstaller=1.28.0=r3.4.1_0
- bioconductor-biocparallel=1.12.0=r3.4.1_0
- bioconductor-biomart=2.34.0=r3.4.1_0
- bioconductor-biostrings=2.46.0=r3.4.1_0
- bioconductor-clusterprofiler=3.6.0=r3.4.1_0
- bioconductor-delayedarray=0.4.1=r3.4.1_0
- bioconductor-deseq2=1.18.1=r3.4.1_0
- bioconductor-do.db=2.9=r3.4.1_0
- bioconductor-dose=3.4.0=r3.4.1_0
- bioconductor-dupradar=1.8.0=r3.4.1_0
- bioconductor-fgsea=1.4.0=r3.4.1_0
- bioconductor-genefilter=1.60.0=r3.4.1_0
- bioconductor-geneplotter=1.56.0=r3.4.1_0
- bioconductor-genomeinfodb=1.14.0=r3.4.1_0
- bioconductor-genomeinfodbdata=0.99.1=r3.4.1_0
- bioconductor-genomicalignments=1.14.0=r3.4.1_0
- bioconductor-genomicfeatures=1.30.0=r3.4.1_0
- bioconductor-genomicranges=1.30.0=r3.4.1_0
- bioconductor-go.db=3.5.0=r3.4.1_0
- bioconductor-gosemsim=2.4.0=r3.4.1_0
- bioconductor-interactivedisplaybase=1.16.0=r3.4.1_0
- bioconductor-iranges=2.12.0=r3.4.1_0
- bioconductor-limma=3.34.1=r3.4.1_0
- bioconductor-qvalue=2.10.0=r3.4.1_0
- bioconductor-rsamtools=1.30.0=r3.4.1_0
- bioconductor-rsubread=1.28.0=r3.4.1_0
- bioconductor-rtracklayer=1.38.0=r3.4.1_0
- bioconductor-s4vectors=0.16.0=r3.4.1_0
- bioconductor-summarizedexperiment=1.8.0=r3.4.1_0
- bioconductor-sva=3.26.0=r3.4.1_0
- bioconductor-tximport=1.6.0=r3.4.1_0
- bioconductor-xvector=0.18.0=r3.4.1_0
- bioconductor-zlibbioc=1.24.0=r3.4.1_0
- biopython=1.70=np112py36_1
- bowtie=1.2.1.1=py36pl5.22.0_0
- bowtie2=2.3.3.1=py36pl5.22.0_0
- cutadapt=1.15=py36_0
- deeptools=2.5.4=py36_0
- fastq-screen=0.11.3=pl5.22.0_0
- fastqc=0.11.5=pl5.22.0_3
- filechunkio=1.6=py36_0
- ftputil=3.2=py36_0
- gat=1.3.5=py36_0
- gffutils=0.9=py36_0
- ghostscript=9.18=1
- hisat2=2.1.0=py36pl5.22.0_0
- htslib=1.5=0
- intervalstats=1.01=0
- jemalloc=4.5.0=0
- kallisto=0.43.1=hdf51.8.17_0
- multiqc=1.3=py36_2
- mysql-connector-c=6.1.6=2
- perl-gd=2.56=pl5.22.0_6
- perl-gdgraph=1.49=pl5.22.0_3
- perl-gdtextutil=0.86=pl5.22.0_3
- picard=2.15.0=py36_0
- py2bit=0.2.2=py36_0
- pybedtools=0.7.10=py36_1
- pybigwig=0.3.6=np112py36_0
- pyfaidx=0.5.1=py36_0
- pysam=0.12.0.1=py36_htslib1.5_1
- pysftp=0.2.9=py36_0
- r-data.table=1.10.4=r3.4.1_0
- salmon=0.8.2=1
- samtools=1.5=1
- simplejson=3.8.1=py36_0
- snakemake=4.3.1=py36_0
- subread=1.5.3=0
- tbb=4.4_20150728=0
- tqdm=4.7.2=py36_0
- ucsc-bedsort=357=0
- ucsc-bedgraphtobigwig=357=0
- ucsc-fetchchromsizes=357=0
- ucsc-gtftogenepred=357=0
- ucsc-liftover=357=0
- ucsc-oligomatch=357=0
- ucsc-twobittofa=357=0
- xopen=0.3.2=py36_0
- aioeasywebdav=2.2.0=py36_0
- aiohttp=2.0.7=py36_0
- apipkg=1.4=py36_0
- appdirs=1.4.3=py_0
- argcomplete=1.8.2=py36_0
- argh=0.26.2=py36_1
- asn1crypto=0.22.0=py36_0
- async-timeout=1.2.1=py36_0
- attrs=17.3.0=py_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- boost=1.63.0=np112py36_6
- boost-cpp=1.63.0=2
- bzip2=1.0.6=1
- ca-certificates=2017.11.5=0
- cairo=1.14.6=4
- certifi=2017.11.5=py36_0
- cffi=1.11.2=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py36_0
- colormath=2.1.1=py36_1
- configargparse=0.12.0=py36_0
- cryptography=2.1.4=py36_0
- curl=7.54.1=0
- cycler=0.10.0=py36_0
- cython=0.27.3=py36_0
- dbus=1.10.22=0
- decorator=4.1.2=py36_0
- docutils=0.14=py36_0
- dropbox=8.4.0=py_0
- execnet=1.5.0=py_0
- expat=2.2.5=0
- fontconfig=2.12.1=6
- freetype=2.7=1
- future=0.16.0=py36_0
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gmp=6.1.2=0
- graphite2=1.3.10=0
- graphviz=2.38.0=5
- gsl=2.1=2
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- harfbuzz=1.4.3=0
- hdf5=1.8.17=11
- icu=58.2=0
- idna=2.6=py36_1
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.10=py36_0
- jpeg=9b=2
- jsonschema=2.6.0=py36_0
- krb5=1.14.2=0
- libffi=3.2.1=3
- libgd=2.2.5=0
- libiconv=1.15=0
- libpng=1.6.28=1
- libssh2=1.8.0=1
- libtiff=4.0.7=0
- libtool=2.4.6=0
- libuuid=1.0.3=1
- libwebp=0.5.2=7
- libxcb=1.12=1
- libxml2=2.9.5=0
- lzstring=1.0.3=py36_0
- markupsafe=1.0=py36_0
- matplotlib=2.1.1=py36_0
- mmtf-python=1.0.9=py_0
- msgpack-python=0.4.8=py36_0
- multidict=2.1.4=py36_0
- ncurses=5.9=10
- networkx=1.11=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2n=0
- pandas=0.21.1=py36_0
- pandoc=2.0.0.1=0
- pango=1.40.4=0
- paramiko=2.3.1=py_0
- patsy=0.4.1=py36_0
- pcre=8.39=0
- perl=5.22.0.1=0
- pexpect=4.3.0=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.3.0=py36_0
- pip=9.0.1=py36_0
- pixman=0.34.0=1
- pluggy=0.6.0=py_0
- prompt_toolkit=1.0.15=py36_0
- psutil=5.4.0=py36_0
- ptyprocess=0.5.2=py36_0
- py=1.5.2=py_0
- pyasn1=0.3.7=py_0
- pycparser=2.18=py36_0
- pygments=2.2.0=py36_0
- pynacl=1.1.2=py36_0
- pyopenssl=17.4.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pysocks=1.6.7=py36_0
- pytest=3.3.1=py36_0
- pytest-forked=0.2=py36_0
- pytest-runner=3.0=py_0
- pytest-xdist=1.20.1=py_0
- python=3.6.3=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.3=py_2
- pyyaml=3.12=py36_1
- qt=5.6.2=3
- r-acepack=1.4.1=r3.4.1_0
- r-assertthat=0.1=r3.4.1_0
- r-backports=1.0.5=r3.4.1_0
- r-base=3.4.1=0
- r-base64enc=0.1_3=r3.4.1_0
- r-bh=1.65.0_1=r3.4.1_0
- r-bindr=0.1=r3.4.1_0
- r-bindrcpp=0.2=r3.4.1_0
- r-bit=1.1_12=r3.4.1_0
- r-bit64=0.9_5=r3.4.1_0
- r-bitops=1.0_6=r3.4.1_0
- r-blob=1.1.0=r3.4.1_0
- r-catools=1.17.1=r3.4.1_0
- r-checkmate=1.8.2=r3.4.1_0
- r-cluster=2.0.6=r3.4.1_0
- r-codetools=0.2_15=r3.4.1_0
- r-colorspace=1.3_2=r3.4.1_0
- r-curl=2.4=r3.4.1_0
- r-dbi=0.6_1=r3.4.1_0
- r-dichromat=2.0_0=r3.4.1_0
- r-digest=0.6.12=r3.4.1_0
- r-doparallel=1.0.10=r3.4.1_0
- r-dplyr=0.7.0=r3.4.1_0
- r-dt=0.2=r3.4.1_0
- r-evaluate=0.10.1=r3.4.1_0
- r-fastmatch=1.1_0=r3.4.1_0
- r-foreach=1.4.3=r3.4.1_0
- r-foreign=0.8_67=r3.4.1_0
- r-formula=1.2_1=r3.4.1_0
- r-futile.logger=1.4.3=r3.4.1_0
- r-futile.options=1.0.0=r3.4.1_0
- r-gdata=2.17.0=r3.4.1_0
- r-getopt=1.20.0=r3.4.1_0
- r-ggplot2=2.2.1=r3.4.1_0
- r-glue=1.1.1=r3.4.1_0
- r-gplots=3.0.1=r3.4.1_0
- r-gridbase=0.4_7=r3.4.1_0
- r-gridextra=2.2.1=r3.4.1_0
- r-gtable=0.2.0=r3.4.1_0
- r-gtools=3.5.0=r3.4.1_0
- r-highr=0.6=r3.4.1_0
- r-hmisc=4.0_3=r3.4.1_0
- r-hms=0.3=r3.4.1_0
- r-htmltable=1.9=r3.4.1_0
- r-htmltools=0.3.6=r3.4.1_0
- r-htmlwidgets=0.9=r3.4.1_0
- r-httpuv=1.3.3=r3.4.1_0
- r-httr=1.2.1=r3.4.1_0
- r-igraph=1.0.1=r3.4.1_0
- r-irlba=2.1.2=r3.4.1_0
- r-iterators=1.0.8=r3.4.1_0
- r-jsonlite=1.4=r3.4.1_0
- r-kernsmooth=2.23_15=r3.4.1_0
- r-knitr=1.16=r3.4.1_0
- r-knitrbootstrap=1.0.1=r3.4.1_0
- r-labeling=0.3=r3.4.1_0
- r-lambda.r=1.1.9=r3.4.1_0
- r-lattice=0.20_34=r3.4.1_0
- r-latticeextra=0.6_28=r3.4.1_0
- r-lazyeval=0.2.0=r3.4.1_0
- r-locfit=1.5_9.1=r3.4.1_0
- r-magrittr=1.5=r3.4.1_0
- r-markdown=0.8=r3.4.1_0
- r-mass=7.3_45=r3.4.1_0
- r-matrix=1.2_7.1=r3.4.1_0
- r-matrixstats=0.52.2=r3.4.1_0
- r-memoise=1.1.0=r3.4.1_0
- r-mgcv=1.8_17=r3.4.1_0
- r-mime=0.5=r3.4.1_0
- r-munsell=0.4.3=r3.4.1_0
- r-nlme=3.1_131=r3.4.1_0
- r-nmf=0.20.6=r3.4.1_0
- r-nnet=7.3_12=r3.4.1_0
- r-openssl=0.9.7=r3.4.1_0
- r-pheatmap=1.0.8=r3.4.1_0
- r-pkgconfig=2.0.1=r3.4.1_0
- r-pkgmaker=0.22=r3.4.1_0
- r-plogr=0.1_1=r3.4.1_0
- r-plyr=1.8.4=r3.4.1_0
- r-prettyunits=1.0.2=r3.4.1_0
- r-progress=1.1.2=r3.4.1_0
- r-r6=2.2.0=r3.4.1_0
- r-rcolorbrewer=1.1_2=r3.4.1_0
- r-rcpp=0.12.13=r3.4.1_0
- r-rcpparmadillo=0.7.800.2.0=r3.4.1_0
- r-rcurl=1.95_4.8=r3.4.1_0
- r-readr=1.1.0=r3.4.1_0
- r-registry=0.3=r3.4.1_0
- r-reshape2=1.4.2=r3.4.1_0
- r-rjson=0.2.15=r3.4.1_0
- r-rlang=0.1.2=r3.4.1_0
- r-rmarkdown=1.6=r3.4.1_2
- r-rmysql=0.10.11=r3.4.1_0
- r-rngtools=1.2.4=r3.4.1_0
- r-rpart=4.1_10=r3.4.1_0
- r-rprojroot=1.2=r3.4.1_0
- r-rsqlite=2.0=r3.4.1_0
- r-rvcheck=0.0.9=r3.4.1_0
- r-scales=0.4.1=r3.4.1_0
- r-shiny=1.0.3=r3.4.1_0
- r-snow=0.4_2=r3.4.1_0
- r-sourcetools=0.1.6=r3.4.1_0
- r-stringi=1.1.2=r3.4.1_0
- r-stringr=1.2.0=r3.4.1_0
- r-survival=2.40_1=r3.4.1_0
- r-tibble=1.3.3=r3.4.1_0
- r-tidyr=0.6.1=r3.4.1_0
- r-viridis=0.4.0=r3.4.1_0
- r-viridislite=0.2.0=r3.4.1_0
- r-xml=3.98_1.6=r3.4.1_0
- r-xtable=1.8_2=r3.4.1_0
- r-yaml=2.1.14=r3.4.1_0
- ratelimiter=1.2.0=py36_0
- readline=6.2=0
- reportlab=3.4.0=py36_0
- requests=2.18.4=py36_1
- seaborn=0.8.1=py36_0
- setuptools=38.2.4=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- spectra=0.0.7=py36_0
- sqlite=3.13.0=1
- statsmodels=0.8.0=py36_0
- tk=8.5.19=2
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.22=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.30.0=py_1
- wrapt=1.10.11=py36_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- yaml=0.1.6=0
- yarl=0.10.0=py36_0
- zlib=1.2.8=3
- bcrypt=3.1.3=py36_0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- markdown=2.6.9=py36_0
- mkl=2017.0.3=0
- numpy=1.12.1=py36_0
- openjdk=8.0.121=1
- scipy=0.19.1=np112py36_0
- wget=1.18=0
- lcdblib=0.1.2.post=py36hb10994e_60
- pip:
  - backports.functools-lru-cache==1.4
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.15

