channels:
  - bioconda
  - conda-forge
  - defaults
  - lcdb
  - jfear
dependencies:
  - atropos=1.1.10
  - bamtools=2.4.1
  - bowtie2=2.3.3.1
  - fastq-screen=0.11.3
  - fastqc=0.11.5
  - hisat2=2.1.0
  - lcdblib=0.1.4.post
  - pandas=0.21.1
  - picard=2.20.8
  - python=3.6.3
  - r-base=3.4.1
  - samtools=1.9
  - subread=1.5.2