jobscript: "../config/slurm/slurm-jobscript.sh"
cluster: "../config/slurm/slurm-submit.py --partition {cluster.partition} --cpus-per-task {threads} --mem {resources.mem_gb}g --time {resources.time_hr}:00:00 --gres 'lscratch:{resources.lscratch}' --output=slurm_logs/{rule}.o.%j --error=slurm_logs/{rule}.e.%j"
cluster-status: "../config/slurm/slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: .01
local-cores: 2
jobs: 999
latency-wait: 120
keep-going: true
rerun-incomplete: true
verbose: true
use-conda: true
use-singularity: true
printshellcmds: true
