name: ncbi_remap
dependencies:
- anaconda-client=1.5.1
- argcomplete=1.0.0
- argh=0.26.1
- bcftools=1.3.1
- beautifulsoup4=4.5.1
- biopython=1.67
- blas=1.1
- blat=35
- blaze=0.10.1
- bokeh=0.12.1
- cairo=1.12.18
- cffi=1.6.0
- chest=0.2.3
- click=6.2
- cloudpickle=0.2.1
- clyent=1.2.2
- cryptography=1.4
- curl=7.45.0
- cycler=0.10.0
- cytoolz=0.8.0
- dask=0.10.2
- datashape=0.5.2
- decorator=4.0.10
- deeptools=2.3.3
- docutils=0.12
- dropbox=5.2.1
- entrypoints=0.2.2
- filechunkio=1.6
- flask=0.11.1
- flask-cors=2.1.2
- fontconfig=2.11.1
- freetype=2.5.5
- ftputil=3.2
- gffutils=0.8.7.1
- glib=2.43.0
- h5py=2.6.0
- harfbuzz=0.9.35
- hdf5=1.8.17
- heapdict=1.0.0
- hisat2=2.0.4
- html5lib=0.999
- htslib=1.3.1
- idna=2.1
- ipykernel=4.4.1
- ipython=5.1.0
- ipython_genutils=0.1.0
- ipywidgets=4.1.1
- itsdangerous=0.24
- jedi=0.9.0
- jinja2=2.8
- jpeg=9b
- jsonschema=2.5.1
- jupyter=1.0.0
- jupyter_client=4.3.0
- jupyter_console=5.0.0
- jupyter_core=4.1.1
- libffi=3.2.1
- libgcc=4.8.5
- libgfortran=3.0.0
- libpng=1.6.22
- libsodium=1.0.10
- libtiff=4.0.6
- libxml2=2.9.3
- libxslt=1.1.28
- llvmlite=0.12.1
- locket=0.2.0
- lxml=3.6.4
- markupsafe=0.23
- matplotlib=1.5.1
- mistune=0.7.2
- mkl=11.3.3
- multipledispatch=0.4.8
- nbconvert=4.2.0
- nbextensions=master
- nbformat=4.0.1
- ncurses=5.9
- networkx=1.11
- notebook=4.2.2
- numba=0.27.0
- numexpr=2.6.1
- numpy=1.11.1
- odo=0.5.0
- openblas=0.2.18
- openssl=1.0.2h
- pandas=0.18.1
- pango=1.36.8
- paramiko=2.0.2
- partd=0.3.5
- path.py=8.2.1
- pcre=8.38
- pexpect=4.0.1
- pickleshare=0.7.3
- pip=8.1.2
- pixman=0.32.6
- prompt_toolkit=1.0.3
- psutil=4.3.0
- ptyprocess=0.5.1
- pyasn1=0.1.9
- pybigwig=0.2.8
- pycparser=2.14
- pyfaidx=0.4.7.1
- pygments=2.1.3
- pyparsing=2.1.4
- pyqt=4.11.4
- pysam=0.9.1
- pysftp=0.2.8
- pytables=3.2.3.1
- python=3.5.2
- python-dateutil=2.3
- pytz=2016.6.1
- pyyaml=3.11
- pyzmq=15.4.0
- qt=4.8.7
- qtconsole=4.2.1
- r=3.2.2
- r-base=3.2.2
- r-boot=1.3_17
- r-class=7.3_14
- r-cluster=2.0.3
- r-codetools=0.2_14
- r-foreign=0.8_66
- r-kernsmooth=2.23_15
- r-lattice=0.20_33
- r-mass=7.3_45
- r-matrix=1.2_2
- r-mgcv=1.8_9
- r-nlme=3.1_122
- r-nnet=7.3_11
- r-recommended=3.2.2
- r-rpart=4.1_10
- r-spatial=7.3_11
- r-survival=2.38_3
- readline=6.2
- requests=2.10.0
- rpy2=2.7.8
- samtools=1.3.1
- scikit-learn=0.17.1
- scipy=0.18.0
- seaborn=0.7.1
- setuptools=25.1.6
- simplegeneric=0.8.1
- simplejson=3.8.1
- sip=4.18
- six=1.10.0
- snakemake=3.7.1
- sqlalchemy=1.0.13
- sqlite=3.13.0
- sratoolkit=2.5.7
- terminado=0.6
- tk=8.5.18
- toolz=0.8.0
- tornado=4.4.1
- traitlets=4.2.2
- urllib3=1.12
- watermark=1.3.1
- wcwidth=0.1.7
- werkzeug=0.11.10
- wheel=0.29.0
- xlwt=1.1.2
- xz=5.2.2
- yaml=0.1.6
- zeromq=4.1.4
- zlib=1.2.8
- pip:
  - greenlet==0.4.10
  - ipycache==0.1.6.dev0
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-contrib-core==0.3.0
  - jupyter-contrib-nbextensions==0.1.0
  - jupyter-core==4.1.1
  - jupyter-nbextensions-configurator==0.2.1
  - msgpack-python==0.4.8
  - nbreport==0.1.1b1
  - neovim==0.1.9
  - prompt-toolkit==1.0.3
  - tables==3.2.3.1

