channels:
- lcdb
- jfear
- bioconda
- r
- defaults
- conda-forge
dependencies:
  - python=3.5
  - ucsc-bedgraphtobigwig=332
  - ucsc-bigwigmerge=332
  - ucsc-bigwigtobedgraph=332
  - lcdblib=0.1.1
  - pysam=0.10.0
  - htslib=1.3.2
  - samtools=1.3.1
  - bamtools=2.4.0
