#sra_file: /data/Oliverlab/project/remap/data/test.txt
sra_file: /data/Oliverlab/project/remap/data/sra_info_dmel_13050.txt
BAM_dir: /data/Oliverlab/project/remap/result/pre_alignment
hisat2_version: 2.0.4
stringtie_version: 1.2.3
samtools_version: 1.3
rseqc_version: 2.6.3
splice_file: /data/Oliverlab/data/FlyBase/FB2015_04/dmel_ERCC.splicesites.txt
hisat2_index: /data/Oliverlab/data/FlyBase/FB2015_04/dmel_ERCC
bed12_file: /data/Oliverlab/data/FlyBase/FB2015_04/dmel_ERCC.bed12
