fn_clean_exts:
  - '_1'
  - '_2'
  - '.md5'
  - '.trim'
  - '.fq'
  - '.infer_experiment'
  - '.bam_stat'
  - '.geneBodyCoverage'
  - '.tin'
  - '.density_'
  - '.expression_'
  - '.multimapping_'
  - '.dupradar_'
  - '.fastq'
  - '.picard'
  - '.gz'
