sampletable: 'sampletable.tsv'

# This can be optionally set as an environment variable, REFERENCES_DIR.
references_dir: "/data/lcdb-references"

# Can either specify full paths, or use the "{references_dir}" placeholder.
aligner_prefix: "{references_dir}/dm6/hisat2/dm6_default"
rrna_prefix: "{references_dir}/dm6/bowtie2/dm6_rRNA"
gtf: "{references_dir}/dm6/gtf/dm6_r6-11.gtf"
