references:
  dmel:
    fasta: ../lcdb-references/dmel/r6-11/fasta/dmel_r6-11.fasta
    gtf:  ../lcdb-references/dmel/r6-11/gtf/dmel_r6-11.gtf
    db:  ../lcdb-references/dmel/r6-11/gtf/dmel_r6-11.gtf.db
    intergenic: ../output/dmel_r6-11.intergenic.gtf
    nonstranded_segments: ../output/nonstranded_exon_segments.gtf
    stranded_segments: ../output/stranded_exon_segments.gtf
    nonstranded_fusions: ../output/nonstranded_exon_fusions.gtf
    stranded_fusions: ../output/stranded_exon_fusions.gtf
    bowtie2: ../lcdb-references/dmel/r6-11/bowtie2/dmel_r6-11.1.bt2
    hisat2: ../lcdb-references/dmel/r6-11/hisat2/dmel_r6-11.1.ht2
    known_splice_sites: "../output/known_splice_sites_r6-11.txt"
    refflat: ../lcdb-references/dmel/r6-11/gtf/dmel_r6-11.refflat
    chromSizes: ../lcdb-references/dmel/r6-11/fasta/dmel_r6-11.chromsizes
    fb_chromSizes: ../output/dmel_r6-11.flybase.chromsizes
    salmon: ../lcdb-references/dmel/r6-11_transcriptome/salmon/dmel_r6-11_transcriptome/hash.bin
  rRNA:
    bowtie2: ../lcdb-references/dmel/rRNA/bowtie2/dmel_rRNA.1.bt2
  wolbachia:
    bowtie2: ../lcdb-references/wolbachia/default/bowtie2/wolbachia_default.1.bt2
  human:
    bowtie2: ../lcdb-references/human/gencode-v19/bowtie2/human_gencode-v19.1.bt2
  ecoli:
    bowtie2: ../lcdb-references/ecoli/default/bowtie2/ecoli_default.1.bt2
  yeast:
    bowtie2: ../lcdb-references/sacCer3/default/bowtie2/sacCer3_default.1.bt2
  phix:
    bowtie2: ../lcdb-references/phix/default/bowtie2/phix_default.1.bt2
  ercc:
    bowtie2: ../lcdb-references/ercc/srm2374/bowtie2/ercc_srm2374.1.bt2
  adapters:
    bowtie2: ../lcdb-references/adapters/default/bowtie2/adapters_default.1.bt2
