__default__:
    mem: '2g'
    time: '4:00:00'
    partition: 'niddk,norm'
    threads: 2
    gres: "lscratch:0"

bigWigMergeToBedGraph:
    mem: '30g'

mergeBam:
    mem: '30g'
    gres: "lscratch:60"

bamToBigWig:
    mem: '30g'
