#sra_file: /data/Oliverlab/project/remap/data/sra_info_dmel_13050.txt
__default__:
    mem: "2g"
    time: "11:00:00"
    gres: "lscratch:50"
    partition: 'norm'

atropos:
  mem: "32g"
  gres: "lscratch:200"

fastq_screen:
    mem: "8g"

feature_counts:
    mem: "8g"

markduplicates:
    mem: "34g"
    time: "48:00:00"

collectrnaseqmetrics_unstrand:
    mem: "34g"
    time: "48:00:00"

collectrnaseqmetrics_first:
    mem: "34g"
    time: "48:00:00"

collectrnaseqmetrics_second:
    mem: "34g"
    time: "48:00:00"

hisat2:
    mem: "34g"
    time: "24:00:00"
    gres: "lscratch:250"
