#sra_file: /data/Oliverlab/project/remap/data/sra_info_dmel_13050.txt
__default__:
    mem: "4g"
    time: "11:00:00"
    gres: "lscratch:100"
    partition: 'niddk,norm'

fastq_clean:
  mem: "32g"

hisat2:
    mem: "80g"
    time: "24:00:00"
    gres: "lscratch:200"
