#sra_file: /data/Oliverlab/project/remap/data/sra_info_dmel_13050.txt
__default__:
    mem: "4g"
    time: "12:00:00"
    gres: "lscratch:0"
    partition: 'niddk,norm'

hisat2:
    mem: "80g"
    time: "24:00:00"
    gres: "lscratch:80"

tin:
    gres: "lscratch:60"

geneBody_coverage:
    gres: "lscratch:60"
