#sra_file: /data/Oliverlab/project/remap/data/sra_info_dmel_13050.txt
__default__:
    mem: "2g"
    time: "4:00:00"
    gres: "lscratch:0"
    partition: 'niddk,norm'

hisat2:
    mem: "10g"
    time: "24:00:00"
    gres: "lscratch:100"

rseqc:
    gres: "lscratch:60"
    mem: "6g"
    time: "8:00:00"
