__default__:
    mem: "8g"
    time: "11:00:00"
    gres: "lscratch:80"
    partition: 'niddk,norm'

atropos:
  mem: "36g"
  gres: "lscratch:200"

hisat2:
    mem: "32g"
    time: "24:00:00"
    gres: "lscratch:200"

featurecounts:
    mem: "8g"
