# Values are from the SRA submission template.G
library_strategy:
  WGA: Random sequencing of the whole genome following non-pcr amplification
  WGS: Random sequencing of the whole genome
  WXS: Random sequencing of exonic regions selected from the genome
  RNA-Seq: Random sequencing of whole transcriptome
  miRNA-Seq: Random sequencing of small miRNAs
  WCS: Random sequencing of a whole chromosome or other replicon isolated from a genome
  CLONE: Genomic clone based (hierarchical) sequencing
  POOLCLONE: Shotgun of pooled clones (usually BACs and Fosmids)
  AMPLICON: Sequencing of overlapping or distinct PCR or RT-PCR products
  CLONEEND: Clone end (5', 3', or both) sequencing
  FINISHING: Sequencing intended to finish (close) gaps in existing coverage
  ChIP-Seq: Direct sequencing of chromatin immunoprecipitates
  MNase-Seq: Direct sequencing following MNase digestion
  DNase-Hypersensitivity: Sequencing of hypersensitive sites, or segments of open chromatin that are more readily cleaved by DNaseI
  Bisulfite-Seq: Sequencing following treatment of DNA with bisulfite to convert cytosine residues to uracil depending on methylation status
  Tn-Seq: Sequencing from transposon insertion sites
  EST: Single pass sequencing of cDNA templates
  FL-cDNA: Full-length sequencing of cDNA templates
  CTS: Concatenated Tag Sequencing
  MRE-Seq: Methylation-Sensitive Restriction Enzyme Sequencing strategy
  MeDIP-Seq: Methylated DNA Immunoprecipitation Sequencing strategy
  MBD-Seq: Direct sequencing of methylated fractions sequencing strategy
  Synthetic-Long-Read: "" 
  ATAC-seq: Assay for Transposase-Accessible Chromatin (ATAC) strategy is used to study genome-wide chromatin accessibility. alternative method to DNase-seq that uses an engineered Tn5 transposase to cleave DNA and to integrate primer DNA sequences into the cleaved genomic DNA
  ChIA-PET: Direct sequencing of proximity-ligated chromatin immunoprecipitates.
  FAIRE-seq: Formaldehyde Assisted Isolation of Regulatory Elements. reveals regions of open chromatin
  Hi-C: Chromosome Conformation Capture technique where a biotin-labeled nucleotide is incorporated at the ligation junction, enabling selective purification of chimeric DNA ligation junctions followed by deep sequencing
  ncRNA-Seq: Capture of other non-coding RNA types, including post-translation modification types such as snRNA (small nuclear RNA) or snoRNA (small nucleolar RNA), or expression regulation types such as siRNA (small interfering RNA) or piRNA/piwi/RNA (piwi-interacting RNA).
  RAD-Seq: "" 
  RIP-Seq: Direct sequencing of RNA immunoprecipitates (includes CLIP-Seq, HITS-CLIP and PAR-CLIP).
  SELEX: Systematic Evolution of Ligands by EXponential enrichment
  ssRNA-seq: strand-specific RNA sequencing
  Targeted-Capture: ""
  Tethered Chromatin Conformation Capture: ""
  OTHER: Library strategy not listed (please include additional info in the “design description”)

library_source:
  GENOMIC: Genomic DNA (includes PCR products from genomic DNA)
  TRANSCRIPTOMIC: Transcription products or non genomic DNA (EST, cDNA, RT-PCR, screened libraries)
  METAGENOMIC: Mixed material from metagenome
  METATRANSCRIPTOMIC: Transcription products from community targets
  SYNTHETIC: Synthetic DNA
  VIRAL RNA: Viral RNA
  GENOMIC SINGLE CELL: ""
  TRANSCRIPTOMIC SINGLE CELL: ""
  OTHER: Other, unspecified, or unknown library source material (please include additional info in the “design description”)

library_selection:
  RANDOM: Random selection by shearing or other method
  PCR: Source material was selected by designed primers
  RANDOM PCR: Source material was selected by randomly generated primers
  RT-PCR: Source material was selected by reverse transcription PCR
  HMPR: Hypo-methylated partial restriction digest
  MF: Methyl Filtrated
  CF-S: Cot-filtered single/low-copy genomic DNA
  CF-M: Cot-filtered moderately repetitive genomic DNA
  CF-H: Cot-filtered highly repetitive genomic DNA
  CF-T: Cot-filtered theoretical single-copy genomic DNA
  MDA: Multiple displacement amplification
  MSLL: Methylation Spanning Linking Library
  cDNA: complementary DNA
  ChIP: Chromatin immunoprecipitation
  MNase: Micrococcal Nuclease (MNase) digestion
  DNAse: Deoxyribonuclease (MNase) digestion
  Hybrid Selection: Selection by hybridization in array or solution
  Reduced Representation: Reproducible genomic subsets, often generated by restriction fragment size selection, containing a manageable number of loci to facilitate re-sampling
  Restriction Digest: DNA fractionation using restriction enzymes
  5-methylcytidine antibody: Selection of methylated DNA fragments using an antibody raised against 5-methylcytosine or 5-methylcytidine (m5C)
  MBD2 protein methyl-CpG binding domain: Enrichment by methyl-CpG binding domain
  CAGE: Cap-analysis gene expression
  RACE: Rapid Amplification of cDNA Ends
  size fractionation: Physical selection of size appropriate targets
  Padlock probes capture method: Circularized oligonucleotide probes
  other: Other library enrichment, screening, or selection process (please include additional info in the “design description”)
  unspecified: Library enrichment, screening, or selection is not specified (please include additional info in the “design description”)
  cDNA_oligo_dT: ""
  cDNA_randomPriming: ""
  Inverse rRNA: depletion of ribosomal RNA by oligo hybridization.
  Oligo-dT: enrichment of messenger RNA (mRNA) by hybridization to Oligo-dT.
  PolyA: PolyA selection or enrichment for messenger RNA (mRNA); should replace cDNA enumeration.
  repeat fractionation: Selection for less repetitive (and more gene rich) sequence through Cot filtration (CF) or other fractionation techniques based on DNA kinetics.

instrument_model:
  _LS454:
    - 454 GS
    - 454 GS 20
    - 454 GS FLX
    - 454 GS FLX+
    - 454 GS FLX Titanium
    - 454 GS Junior
  ABI_SOLID:
    - AB 5500 Genetic Analyzer
    - AB 5500xl Genetic Analyzer
    - AB 5500x-Wl Genetic Analyzer
    - AB SOLiD 3 Plus System
    - AB SOLiD 4 System
    - AB SOLiD 4hq System
    - AB SOLiD PI System
    - AB SOLiD System
    - AB SOLiD System 2.0
    - AB SOLiD System 3.0
  BGISEQ:
    - BGISEQ-500
  CAPILLARY:
    - AB 310 Genetic Analyzer
    - AB 3130 Genetic Analyzer
    - AB 3130xL Genetic Analyzer
    - AB 3500 Genetic Analyzer
    - AB 3500xL Genetic Analyzer
    - AB 3730 Genetic Analyzer
    - AB 3730xL Genetic Analyzer
  COMPLETE_GENOMICS:
    - Complete Genomics
  HELICOS:
    - Helicos HeliScope
  ILLUMINA:
    - HiSeq X Five
    - HiSeq X Ten
    - Illumina Genome Analyzer
    - Illumina Genome Analyzer II
    - Illumina Genome Analyzer IIx
    - Illumina HiScanSQ
    - Illumina HiSeq 1000
    - Illumina HiSeq 1500
    - Illumina HiSeq 2000
    - Illumina HiSeq 2500
    - Illumina HiSeq 3000
    - Illumina HiSeq 4000
    - Illumina iSeq 100
    - Illumina NovaSeq 6000
    - Illumina MiniSeq
    - Illumina MiSeq
    - NextSeq 500
    - NextSeq 550
  ION_TORRENT:
    - Ion Torrent PGM
    - Ion Torrent Proton
    - Ion Torrent S5 XL
    - Ion Torrent S5
  OXFORD_NANOPORE:
    - GridION
    - MinION
    - PromethION
  PACBIO_SMRT:
    - PacBio RS
    - PacBio RS II
    - PacBio Sequel
    - PacBio Sequel II

