restart-times: 3
jobscript: "../config/slurm2/slurm-jobscript.sh"
cluster: "../config/slurm2/slurm-submit.py"
cluster-status: "../config/slurm2/slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: .01
local-cores: 2
latency-wait: 120
jobs: 999
keep-going: true
rerun-incomplete: true
verbose: true
use-conda: true
use-singularity: true
printshellcmds: true
