channels:
  - conda-forge
  - bioconda
  - defaults
  - lcdb
  - jfear
dependencies:
  - atropos=1.1.25
  - bamtools=2.5.1
  - bowtie2=2.3.5.1
  - deeptools=3.3.2
  - fastq-screen=0.13.0
  - fastqc=0.11.9
  - feather-format=0.4.0
  - gffutils=0.10.1
  - hisat2=2.1.0
  - matplotlib=3.1.3
  - nltk=3.4.5
  - numpy=1.18.1
  - pandas=1.0.2
  - picard=2.21.8
  - pint=0.11
  - pyarrow=0.16.0
  - pybedtools=0.8.1
  - pymongo=3.10.1
  - python=3.7.3
  - r-base=3.5.1
  - samtools=1.10
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - snakemake=5.10.0
  - sra-tools=2.10.1
  - sramongo=1.2.0
  - statsmodels=0.11.1
  - subread=1.6.4
  - svgutils=0.3.1
  - ucsc-bedgraphtobigwig=357
  - ucsc-bedsort=357
  - umap-learn=0.3.10
