"""A Subworkflow for downloading and processing FASTQ files."""
import os

# Setup tempdir to work with lscratch
if os.getenv("SLURM_JOBID"):
    TMPDIR = os.path.join('/lscratch', os.getenv('SLURM_JOBID'))
else:
    TMPDIR = os.getenv('TMPDIR', "/tmp")

shell.prefix(f"set -euo pipefail; export TMPDIR={TMPDIR};")

rule se_example:
    input: 
        layout="../output/fastq-wf/fastq_info/SRR031744/LAYOUT",
        summary="../output/fastq-wf/fastq_info/SRR031744/summary.tsv"


rule pe_example:
    input: 
        layout="../output/fastq-wf/fastq_info/SRR031714/LAYOUT",
        summary="../output/fastq-wf/fastq_info/SRR031714/summary.tsv"

include: "rules/download_fastq.smk"
