sex:
  - "sex"
  - "gender"
  - "gender/age"
  - "mating status"
  - "Sex"
  - "sex/age"

developmental_stage:
  - "developmental stage"
  - "developmental_stage"
  - "dev_stage"
  - "Age"
  - "age"
  - "age of flies"
  - "age of fly in days post eclosion"
  - "ages"
  - "days after eclosion"
  - "dev-stage"
  - "developemntal stage"
  - "development stage"
  - "developmental time"
  - "developmental time point"
  - "DevelopmentalStage"
  - "develpomental stage"
  - "embryonic stage"
  - "Stage"
  - "time point"
  - "time"
  - "time-point"
  - "timepoint"

tissue:
  - "tissue"
  - "body_site"
  - "cell/tissue type"
  - "midgut region"
  - "muscle type"
  - "organism part"
  - "OrganismPart"
  - "tissue source"
  - "tissue type"
  - "tissue/cell type"
  - "tissue_type"

cell_type:
  - "cell_type"
  - "cell type"
  - "cell class"
  - "cell line"
  - "cell line background"
  - "cell subtype"
  - "cell_line"
  - "cells"

ignore:
  - "adapter"
  - "adapter_barcode"
  - "agent"
  - "Alias"
  - "Alternate Taxon ID 1"
  - "Alternate Taxon ID 2"
  - "amplification"
  - "antibody"
  - "assay"
  - "background strain"
  - "barcode"
  - "barcode-kit"
  - "batch"
  - "biological replicate"
  - "Biological Replicate"
  - "biological replicate number"
  - "biomarker"
  - "biomaterial provider"
  - "biomaterial_provider"
  - "bioproject_id"
  - "BioprojectID"
  - "biorep"
  - "BioSampleModel"
  - "birth_date"
  - "birth_location"
  - "bloomington stock center id"
  - "breed"
  - "breeding_history"
  - "breeding_method"
  - "Broker name"
  - "cage"
  - "carrier species"
  - "cell passages"
  - "cell type marker"
  - "cell_subtype"
  - "cells derived from"
  - "checksum"
  - "chip antibody"
  - "chip or ip antibody"
  - "collected_by"
  - "collection date"
  - "collection_date"
  - "compound"
  - "condition"
  - "crosses"
  - "cultivar"
  - "culture condition"
  - "culture_collection"
  - "culture_collection"
  - "custom name"
  - "days after treatment"
  - "days at 29 c"
  - "days post infection"
  - "death_date"
  - "Description"
  - "developmental temperature"
  - "dgrp line"
  - "diet"
  - "Diet"
  - "directional"
  - "disease"
  - "disease_stage"
  - "dissection"
  - "dmso"
  - "drosdel deficiency"
  - "drosdel id"
  - "drug for synchronization"
  - "dstim knockdown status"
  - "ecotype"
  - "embryonic temperature"
  - "ENA checklist"
  - "environment (biome)"
  - "environment (feature)"
  - "environment (material)"
  - "ercc infomation"
  - "ercc_pool"
  - "evolutionary_regime"
  - "experiment"
  - "experimental procedure"
  - "experimental_population"
  - "expression"
  - "exptgroup"
  - "external rna control"
  - "extraction method"
  - "extraction protocol"
  - "facs-sorted cells"
  - "fastqs from"
  - "fed on"
  - "fed with"
  - "feeding type"
  - "female genotype"
  - "file no."
  - "fixation"
  - "flag"
  - "flow cell"
  - "fluorescent cell marker"
  - "fly genotype"
  - "fly knockdown gene"
  - "fly knockdown vdrc line"
  - "fly line"
  - "fly/stock id"
  - "flybase species id"
  - "food"
  - "food"
  - "fraction"
  - "full genotype"
  - "gal4 line"
  - "generation"
  - "genetic background"
  - "genetic cross"
  - "genetic modification"
  - "genotype"
  - "Genotype"
  - "genotype of male the female mated with"
  - "genotype/variation"
  - "geo_loc_name"
  - "geographic location (country and/or sea)"
  - "geographic location (latitude)"
  - "geographic location (longitude)"
  - "germline knock-down"
  - "germline knockdown and other transgenes"
  - "grandparental obesity"
  - "group"
  - "growth condition"
  - "growth conditions"
  - "growth protocol"
  - "growth_protocol"
  - "guide rna"
  - "health_state"
  - "heat_hours"
  - "hormone for culture"
  - "host"
  - "host-associated environmental package"
  - "hours at restrictive temperature"
  - "human genotype"
  - "human knockdown gene"
  - "iclip barcode"
  - "illumina barcode"
  - "incubation time"
  - "Index"
  - "infect"
  - "infection"
  - "infection status"
  - "infection time"
  - "injected with"
  - "injury"
  - "input rna volume"
  - "INSDC center alias"
  - "INSDC center name"
  - "INSDC first public"
  - "INSDC last update"
  - "INSDC status"
  - "investigation type"
  - "ip antibody"
  - "isolate"
  - "isolation_source"
  - "knockdown"
  - "label"
  - "lane"
  - "Lane"
  - "lat_lon"
  - "length of culture"
  - "library prep protocol"
  - "library preparation method"
  - "library selection"
  - "library source"
  - "library strategy"
  - "library-kit"
  - "line"
  - "Line"
  - "line source"
  - "machine"
  - "male mate population"
  - "marker"
  - "maternal genotype"
  - "mating system"
  - "mean insert size"
  - "microbiome status"
  - "molecule subtype"
  - "normalization"
  - "Notes"
  - "number cells"
  - "oleic acid"
  - "organism"
  - "original pipeline"
  - "paired or single-end"
  - "parental heterozygosity"
  - "parental obesity"
  - "passage"
  - "passages"
  - "PE read length (bp)"
  - "phenotype"
  - "plasmid"
  - "plate and well id"
  - "platform"
  - "population"
  - "population replicate"
  - "population_diet"
  - "project name"
  - "protocol"
  - "pull-down tag"
  - "pulldown"
  - "purified length"
  - "quality"
  - "qualscores"
  - "quantity"
  - "radiation dose"
  - "random barcode"
  - "reared on"
  - "repeat"
  - "replicate"
  - "Replicate"
  - "Replicate no."
  - "replicates"
  - "resistance"
  - "rin"
  - "rip antibody"
  - "RIP antibody"
  - "rna extracted from"
  - "rna quantity"
  - "rna source"
  - "RNAi"
  - "RNAi driver"
  - "RNAi reagent from harvard drosophila rnai screening center"
  - "RNAi target gene name"
  - "RNAi treatment"
  - "rrna depletion method"
  - "rt primer with random barcode / index"
  - "Run no."
  - "s2 treatment"
  - "sample comment"
  - "sample extraction method"
  - "sample group"
  - "Sample Name"
  - "sample type"
  - "sample_name"
  - "sample_title"
  - "sample_type"
  - "selection"
  - "selection method"
  - "Sequencer"
  - "sequencing method"
  - "sex composition"
  - "shRNA"
  - "silencing"
  - "similar to"
  - "sirna knockdown of"
  - "source"
  - "source developmental stage"
  - "source_name"
  - "species"
  - "specimen with known storage state"
  - "specimen_voucher"
  - "SRA accession"
  - "stable line"
  - "starvation status"
  - "stimulation"
  - "stock"
  - "store_cond"
  - "strain"
  - "strain background"
  - "strain information"
  - "strain origin"
  - "strain/background"
  - "strain/genotype"
  - "strain/sex"
  - "strain/stock"
  - "StrainOrLine"
  - "strandedness"
  - "stress"
  - "stud_book_number"
  - "subcellular fraction"
  - "subregion"
  - "tag"
  - "target molecule"
  - "technical replicate"
  - "technical replicates pooled together"
  - "techrep"
  - "temperature"
  - "temperature shift"
  - "temperature tested"
  - "time of treatment"
  - "time post-treatment"
  - "time_point"
  - "timepoint/developmental stage"
  - "tissue-specific knockdown"
  - "Title"
  - "training"
  - "transfected sirna"
  - "transfected with"
  - "transfecting vector"
  - "transfector"
  - "treated with"
  - "treatment"
  - "treatment duration"
  - "tribe expression"
  - "tribe protein expression"
  - "type"
  - "variation"
  - "vdrc genetic background"
  - "vdrc transformant id"
  - "x chromosome dose"
  - "zygotic genotype"
