cell class:
  3-86-GAL4: 
  CG0239-GAL4/UAS-GFP Background: 
  DAL (G0431-GAL4): 
  DAL-GAL4/UAS-GFP Background: 
  G386-GAL4/UAS-GFP Background: 
  Gamma Kenyon Cells (NP1131-GAL4): 
  NP1131-GAL4/UAS-GFP Background: 
  R27G01-GAL4: 
  R27G01-GAL4/UAS-GFP Background: 
  R71D08-GAL4/UAS-GFP Background: 
  UAS-GFP Background: 
  V2 (R71D08-GAL4): 
  V3 (CG0239-GAL4): 
  alpha/beta Kenyon Cells (c739-GAL4): 
  c739-GAL4/UAS-GFP Background: 
cell line:
  1182-4H: 
  129S1 x Cast with randomly integrated full-length Xist transgene: 
  BG3: 
  BG3 cell line: 
  BG3 cells: 
  BG3-c2: 
  C3H10T1/2: 
  CME W2: 
  CME-L1: 
  CME-W1-Cl.8+: 
  CME-W1-cl8+ wing-disc cell line: 
  CME_L1: 
  CME_W1_Cl.8+: 
  Cal27: 
  Cl.8: 
  D.Mel-2: 
  DL1: 
  DL1 cells: 
  DM: 
  DRSC-S2: 
  DRSC-S2 cell line: 
  DT40: 
  Dm-D17-c3 third instar larva cell line: 
  DmBG3-c2: 
  Dmd20 cell line: 
  Dmd32 cell line: 
  Dmd4 cell line: 
  Dmel-2: 
  Drosophila S2 cells: 
  ESC line V6.5 1A: 
  EZ2-2 ; E(z) temperature sensitive cells: 
  EZ2-2; E(z) temperature sensitive cells: 
  Fadu: 
  Female Head: 
  G2: 
  GM2: 
  HCEC: 
  HCT116: 
  HEK: 
  HEK 293T: 
  HEK-293T and S2: 
  HEP-2 Cells and Drosophila S2 Cells: 
  HEp-2: 
  HEp-2 cells: 
  KC: 
  KC167: 
  Kc: 
  Kc cells: 
  Kc-Rubin: 
  Kc167: 
  Kc167 Drosophila Embryonic: 
  Kc167 Drosophila Embryonic Cell line: 
  Kc167 cells: 
  L2-4: 
  L2-4 Flag-HA-HMR/pMT Hygro+Myc-LHR/pMT Hygro: 
  ML-DmBG1-c1: 
  ML-DmBG3-c2: 
  ML-DmD16-c3: 
  ML-DmD20-c5: 
  ML-DmD21: 
  ML-DmD32: 
  ML-DmD8: 
  ML-DmD9: 
  Mbn2: 
  ModENCODE S2-DRSC (lot 181A1): 
  None: None
  OSC: 
  OSC (Ovarian Somatic Cell): 
  OSC (Ovarian Somatic Cells): 
  OSS: 
  OSS cell line: 
  Ovary: 
  Ovary Somatic Sheet (OSS): 
  Ovary somatic sheet cells (OSS): 
  Pcgf1/3/5/2fl/fl: 
  Pcgf1/3/5/6fl/fl: 
  Pcgf1/3/5fl/fl: 
  Pcgf1fl/fl: 
  Pcgf3/5fl/fl: 
  Pcgf3fl/fl: 
  Pcgf4-/-;Pcgf2fl/fl: 
  Pcgf5fl/fl: 
  Pcgf6fl/fl: 
  PnM: 
  Psc4-1: 
  R1: 
  R4: 
  R5: 
  Ras3: 
  RasV12 cells (R3): 
  RasV12 cells (R7): 
  Ring1a-/-;Ring1bfl/fl: 
  S-2R+: 
  S1: 
  S12-26I3: 
  S2: 
  S2 (Schneider cells): 
  S2 Cells: 
  S2 DRSC: 
  'S2 DRSC: Schneiders line 2': 
  S2 Schneider cells: 
  S2 cell line: 
  S2 cells: 
  S2 experssing biotin-PH: 
  S2 expressing Ph-ML (SAM mutant): 
  S2 expressing Ph-wild type: 
  S2, ATCC, CLR-1963, Lot#5054622: 
  S2-DGRC: 
  S2-DGRC cells: 
  S2-DRSC: 
  S2-DRSC cells: 
  S2-HDR: 
  S2-NP: 
  S2-NP cells: 
  S2-Rubin: 
  S2R: 
  S2R+: 
  S2R+ Cells: 
  S2R+ cell line: 
  S2R+ cells: 
  S2R+ embryonic cell line: 
  S3: 
  S3 cell line: 
  SCC-4: 
  SKN-3: 
  SL2: 
  SR2+: 
  STAT492E: 
  Schneider 2 cell-line: 
  Schneider 2 cells: 
  Schneider Line 2 (S2): 
  Sg4: 
  Testis: 
  Transgenic fly line of Hsp70 10 bp insert promoter: 
  Transgenic fly line of Hsp70 5 bp insert promoter: 
  Transgenic fly line of Hsp70 wild type promoter: 
  WRR-1 cells: 
  cl.8+: 
  clone 8: 
  cmel1 cell line: 
  fGS/OSS: 
  gm2 cell line: 
  hemocyte-like cell line S2: 
  kc167: 
  late embryo-derived cell line: 
  late embryo-derived cell line stably transfected with HA::AbdA: 
  late embryo-derived cell line stably transfected with HA::Ubx: 
  mbn2 cell line: 
  mldmd16_c3 cell line: 
  n/a: None
  ovarian somatic sheath cells (OSS): 
cell line background:
  S2: 
cell subtype:
  dsbarc S2 cells: 
  dsmCherry S2 cells: 
cell type:
  0-2 hour embryo: 
  0-24 hr;OregonR;embryos: 
  0-24 hr;P[Cid-GFP]8-10;embryos: 
  16C follicle cells of the ovary: 
  AKHR neuron: 
  All antennal/eye cell types: 
  B220+CD43+ B cells: 
  BG3: 
  C2: 
  C3: 
  C3H embryo-derived mesenchymal progenitor cells: 
  ? 'C3H10T1/2: C3H embryo-derived mesenchymal progenitor cells; S2: derived from
    a primary culture of late stage (20-24 hours old) Drosophila melanogaster embryos'
  : 
  C57BL/6 x 129S4/SvJae F1 embryo-derived embryonic stem cells: 
  CD2-negative: 
  CD2-positive: 
  CNS midline: 
  Cap cells and terminal filament cells: 
  Cultured Cells: 
  D+ INP: 
  DA neurons: 
  DH44 neuron: 
  Dm12: 
  Dm2: 
  Dm8: 
  Drosophila Embryonic Cell Line: 
  Drosophila S2-NP cells: 
  Drosophila Schneider 2 cells: 
  Drosophila melanogaster cell line: 
  Drosophila ovarian somatic cell: 
  E10::EGFP positive: 
  Elav+ neurons of larval central brain: 
  Embryo derived cells: 
  Embryonic: 
  Embryonic Cell: 
  Embryonic Cell Line: 
  Embryonic cells: 
  Embryonic derived: 
  Embryonic stem cell and S2 cell line: 
  Enteroblasts: 
  Enterocytes: 
  Escort cells and early follicle cells: 
  Esg+ stem-Progenitor cells: 
  Ey+ INP: 
  FACS Sorted midgut progenitor cells: 
  Female Embryonic cell line: 
  Fuss expressing neurons: 
  GABAergic neuron (GAD gal4 driver): 
  GFP labeled regenerating blastema cells: 
  GFP labeled wing disc pouch cells: 
  GFP-positive FACS-sorted cells from brains of 3rd instar larva: 
  GMC: 
  Ganglion mother cells / newly born neurons: 
  Grh+ INP: 
  Hemocytes (HC): 
  HepG2 + Mouse liver + S2 cells: 
  Intestinal Stem Cells: 
  Intestinal stem cells: 
  Kc: 
  Kc cells: 
  Kc cells in interphase: 
  Kc cells in mitosis: 
  Kc167: 
  Kc167 Drosophila Embryonic Cell Line: 
  Kc167 Drosophila Embryonic Cell line: 
  Kc167 cells: 
  Kenyon cell subtype alpha.beta.c: 
  Kenyon cell subtype alpha.beta.p: 
  Kenyon cell subtype alpha.beta.s: 
  Kenyon cell subtype alphap.betap.ap_m: 
  Kenyon cell subtype alphap.betap.m: 
  Kenyon cell subtype gamma.d: 
  Kenyon cell subtype gamma.m_d: 
  LNv neurons: 
  Lamina neurons: 
  Late embryonic derived S2 cells: 
  Late-stage embryonic plasmatocyte: 
  Lawf1: 
  Lawf2: 
  ML-DmBG3-c2: 
  Mi1: 
  Midgut progenitor cells: 
  Mouse embryonic stem cells (mESCs): 
  Neural stem cells: 
  Neuroblasts: 
  Neurons: 
  Non-caudal visceral mesoderm (CVM) cells: 
  Non-hemocytes (HC): 
  Non-midline: 
  OK107: 
  OK107-GAL4 cells: 
  OSC: 
  OSC cells: 
  Optic lobe neurons: 
  Ovarian Somatic Cells: 
  Ovarian Somatic Cells (OSC): 
  Ovarian Somatic Cells (OSCs): 
  Ovarian Somatic Sheet cells (OSS): 
  Ovarian somatic cell: 
  Ovaries: 
  Ovary follicle cells: 
  PDF+ neurons: 
  Patient-derived head and neck squamous cell carcinoma cell line: 
  Photoreceptor neurons: 
  Pseudomonas entomophila infected Midgut progenitor cells: 
  R57C10: 
  R57C10-GAL4 cells: 
  Repo+ glial cells of larval central brain: 
  S2: 
  S2 (Schneider 2 cells): 
  S2 Schneider cells: 
  S2 cell: 
  S2 cell line: 
  S2 cells: 
  S2 late embryonic cells: 
  S2-DRSC cells: 
  S2; Schneiders Drosophila Line 2; Marco Blanchettes Lab: 
  S2; Schneider's Drosophila Line 2;  Marco Blanchette's Lab: 
  S2R: 
  S2R+: 
  S2R+ Cells: 
  S2R+ cell: 
  S2R+ cells: 
  S3: 
  S3 late embryonic cells: 
  Salivary Gland Cells: 
  Scheiders S2 cells: 
  Schneider 2 (S2) cells: 
  Schneider 2 cells: 
  Schneider line 2 (S2) cells: 
  Stably transfected HA-tagged SIN3 187 cells: 
  Stably transfected HA-tagged SIN3 220 cells: 
  T1: 
  T1 and Tm1: 
  T2: 
  T3: 
  T4/T5 neurons: 
  T5: 
  TRH-Gal4 GFP labeled neurons: 
  TRiP Attp2 adult hemocytes: 
  TRiP HMS00478 adult hemocytes: 
  Tdc2: 
  Tdc2-GAL4 cells: 
  Tm2: 
  Tm3: 
  Tm5ab: 
  Tm5c: 
  Tm9: 
  Type I neuroblasts: 
  Type II neuroblasts: 
  Whole dissected ovaries: 
  Whole embryos: 
  all cells in brain: 
  all embryonic cells: 
  astrocyte: 
  bam testis: 
  caudal visceral mesoderm (CVM) cells: 
  chicken B-cell line: 
  cholinergic neuron (Cha gal4 driver): 
  circadian neuron (pdf gal4 driver): 
  cultured cells of embryonic origin: 
  cystoblast: 
  cytoplasm: 
  dissociated cells: 
  dopaminergic neuron (TH gal4 driver): 
  drosophila melanogaster dorsal closure stage embryonal cell line: 
  dvpdf neurons: 
  early mitotically dividing germline cells (gonioblasts): 
  elav positive neurons: 
  elav+ neuron cells: 
  embryo: 
  embryo-derived: 
  embryonal extract: 
  embryonic: 
  embryonic (established from 6-12hours embryo): 
  embryonic cell: 
  embryonic cells: 
  enteroblast: 
  enterocyte: 
  epithelial cells: 
  epithelial, late stage embryo: 
  eye progenitor cells: 
  fat body: 
  female fly abdomen: 
  female germline stem cell: 
  female late embryo-derived cell line: 
  fly ovaries: 
  follicle cells: 
  germ cells: 
  germ line and somatic cells: 
  germline stem cell (GSC): 
  glia: 
  glia and neurons: 
  gonioblasts to mature sperms: 
  head: 
  head extract: 
  hemocyte-like cell line: 
  human colonic epithelial cell line: 
  human colorectal carcinoma cell line: 
  intestinal progenitor cells: 
  intestinal stem cells (ISC): 
  intestinal stem cells/progenitor cells: 
  larval L3, central nervous system: 
  larval central brain: 
  larval fat bodies: 
  late embryonic cells: 
  late embryonic stage cells: 
  late embryonic stage derived cells: 
  lung epithelial cells from a carcinoma: 
  macrophage-like: 
  male, see Schneider's Drosophila Line 2 [D. Mel. (2), SL2] (ATCC CRL-1963): 
  mef2+ muscle cells: 
  mesoderm: 
  midgut: 
  mitochondria: 
  mixed cell types from whole head: 
  modENCODE isolate of Schneider's line 2: 
  nSyb positive neurons: 
  neuroblast: 
  neuroblast (sorted wor-gal:UAS-DsRed nuclei): 
  neuroblasts: 
  neuron: 
  neuron (differentiated daughter cells): 
  neuron (elav gal4 driver): 
  neuronal: 
  neurons: 
  olfactory projection neuron: 
  olfactory projection neuron innervating DA1, VA1d, or DC3 glomerulus: 
  olfactory projection neuron innervating VM2 glomerulus: 
  olfactory projection neuron innvervating DC2 glomerulus: 
  oocytes: 
  ovarian follicle cell: 
  ovarian follicle cell culture: 
  ovarian somatic cell: 
  ovarian somatic cell (OSC): 
  ovarian somatic cell culture: 
  ovarian somatic cell line: 
  ovariectomized carcass: 
  pharate: 
  photoreceptor neurons: 
  primary spermatocytes: 
  retinal cone cells: 
  retinal photoreceptors: 
  s2 cell: 
  sNPFR-Gal4 GFP labeled neuron: 
  sNPFR-Gal4 GFP labeled neurons: 
  somatic cell: 
  sorted primary mesodermal: 
  transfected OSCs: 
  tumor neuroblasts: 
  type II NBs/INPs/GMCs (no neurons): 
  type II NBs/NB-like revertant cells/INPs: 
  type II neuroblast: 
  w1118: 
  whole brain: 
  whole flies: 
  wing disc derived: 
cell_line:
  1182-4H: 
  CCa: 
  CME L1: 
  CME W1 Cl.8+: 
  CME W2: 
  D1: 
  DX: 
  Drosophila S2: 
  Drosophila Schneider 2 (S2)Cells: 
  E-CS: 
  E-OR: 
  G1: 
  G2: 
  GM2: 
  GM3: 
  Jupiter: 
  Kc: 
  Kc167: 
  MCW12: 
  ML-DmBG1-c1: 
  ML-DmBG2-c2: 
  ML-DmBG3-c2: 
  ML-DmD1-c4: 
  ML-DmD11: 
  ML-DmD17-c3: 
  ML-DmD20-c5: 
  ML-DmD21: 
  ML-DmD23-c4: 
  ML-DmD4-c1: 
  ML-DmD8: 
  ML-DmD9: 
  ML83-26: 
  N/A: None
  Not applicable: None
  OSS: 
  Ovarian somatic cell: 
  Ovarian somatic sheet cell: 
  PR8: 
  Pten X: 
  Ras[V12]-H3: 
  Ras[V12]-H7: 
  Ras[V12]; wts[RNAi]: 
  S1: 
  S2: 
  S2 Cells: 
  S2 cell: 
  S2 cells: 
  S2-DRSC: 
  S2-DRSC cells: 
  S2R+: 
  S2_c1: 
  S3: 
  SL2: 
  Schneider 2 Cells S2: 
  Sg4: 
  loqs-5: 
  mbn2: 
  not applicable: None
  rumi[26] Ras[V12]-4: 
cell_type:
  CySC: 
  Follicle cell: 
  Intestinal Stem Cell (ISC): 
  Mcrophage-like cell line: 
  N/A: None
  NA: None
  S2: 
  S2 cell: 
  S2-DRSC cells: 
  S2-cell: 
  all midgut cells: 
  cloned embryonic: 
  dsRNA soaking: 
  embryo: 
  epithelial cell: 
  esg cells: 
  follicular somatic cells: 
  gut: 
  hemocyte: 
  not applicable: None
  other: 
  ovary: 
  whole embryo cells: 
  whole fly: 
cells:
  S2: 
  S2 cells: 
